// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPXG3xrs3s3yclOJk14iA8D1Hjnn8V94',
    appId: '1:482652822905:web:f49eaf6d5fb0f3004ce3a8',
    messagingSenderId: '482652822905',
    projectId: 'readtrack-b8247',
    authDomain: 'readtrack-b8247.firebaseapp.com',
    storageBucket: 'readtrack-b8247.firebasestorage.app',
    measurementId: 'G-MP380PYQ7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31bp82tUfC2anYfUuy4bMdbS3n8Jqyr8',
    appId: '1:482652822905:android:e21da41f169bf7fb4ce3a8',
    messagingSenderId: '482652822905',
    projectId: 'readtrack-b8247',
    storageBucket: 'readtrack-b8247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9Rt7pojsMDcj19Yno1lsjRapD3Jxm6k',
    appId: '1:482652822905:ios:6e43efcb5677feef4ce3a8',
    messagingSenderId: '482652822905',
    projectId: 'readtrack-b8247',
    storageBucket: 'readtrack-b8247.firebasestorage.app',
    iosBundleId: 'com.readtrack.app',
  );
}
